# Generated by Django 4.2 on 2024-06-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
